Received: from zproxy.gmail.com (zproxy.gmail.com [64.233.162.198])
	by wasabi.infohazard.org (Postfix) with ESMTP id BF2D5179852C
	for <jeff@infohazard.org>; Tue, 21 Mar 2006 20:26:12 -0800 (PST)
Received: by zproxy.gmail.com with SMTP id n29so56883nzf
        for <jeff@infohazard.org>; Tue, 21 Mar 2006 20:12:44 -0800 (PST)
DomainKey-Signature: a=rsa-sha1; q=dns; c=nofws;
        s=beta; d=gmail.com;
        h=received:message-id:date:from:to:subject:mime-version:content-type:content-transfer-encoding:content-disposition;
        b=EuGWKBeCoIk0DNGx6/ZQbQB0Q4VmAB0e28f2uZtWCIhvKVqiyBZ/yHw6+yZt1B20iVV4v8t6q6ywfr6StfTQfV8uEdh4ofc2OUdbtpr6fsUWzSLLBpce6dsGLOW9UrBGOLuIsB+58v7GEl8NRzeNT0xXpVKyadtpz5JQ7utsbWI=
Received: by 10.65.204.15 with SMTP id g15mr333946qbq;
        Tue, 21 Mar 2006 20:12:44 -0800 (PST)
Received: by 10.65.241.4 with HTTP; Tue, 21 Mar 2006 20:12:44 -0800 (PST)
Message-ID: <540eb7210603212012we69b3c0qba03eadf1963e750@mail.gmail.com>
Date: Tue, 21 Mar 2006 20:12:44 -0800
From: "Jeff S" <lhoriman@gmail.com>
To: "Jeff S" <jeff@infohazard.org>
Subject: simple test message
MIME-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

This is the body of a simple test message.
