Received: from wproxy.gmail.com (wproxy.gmail.com [64.233.184.201])
	by wasabi.infohazard.org (Postfix) with ESMTP id 5EE7C1798769
	for <jeff@infohazard.org>; Wed, 22 Mar 2006 16:02:24 -0800 (PST)
Received: by wproxy.gmail.com with SMTP id 67so602038wri
        for <jeff@infohazard.org>; Wed, 22 Mar 2006 15:48:47 -0800 (PST)
DomainKey-Signature: a=rsa-sha1; q=dns; c=nofws;
        s=beta; d=gmail.com;
        h=received:message-id:date:from:to:subject:in-reply-to:mime-version:content-type:content-transfer-encoding:content-disposition:references;
        b=G56yqbbSWos+tIgMeEqkw98ON04/Byo6GpnnAZDRjlPTPfO5tp+pQiAAkSUsnFpuZWGxORrQLFQn65qgBXG/mtmPGMY2EQyUyEkOuD/6dr60HwbfoqyYA8j5gNnkKX0407aSJtrYjo/I8T+PJTrn8csDkpOn8XPkSc5uAXTYJpk=
Received: by 10.65.123.2 with SMTP id a2mr118544qbn;
        Wed, 22 Mar 2006 15:48:47 -0800 (PST)
Received: by 10.64.148.12 with HTTP; Wed, 22 Mar 2006 15:48:47 -0800 (PST)
Message-ID: <540eb7210603221548r7b998543hbf840b4f550efb9b@mail.gmail.com>
Date: Wed, 22 Mar 2006 15:48:47 -0800
From: "Jeff S" <lhoriman@gmail.com>
To: "Jeff Schnitzer" <jeff@infohazard.org>
Subject: Re: simple test message
In-Reply-To: <4421E23C.2010206@infohazard.org>
MIME-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline
References: <540eb7210603212012we69b3c0qba03eadf1963e750@mail.gmail.com>
	 <4421E23C.2010206@infohazard.org>

Reply 2

On 3/22/06, Jeff Schnitzer <jeff@infohazard.org> wrote:
> Reply 1
>
> Jeff S wrote:
> > This is the body of a simple test message.
> >
>
>
